language: java

sudo: false

env:
  global:
    - JACOCO_VERSION=0.7.4.201502262128

jdk:
  - oraclejdk7

before_script:
  - "mvn clean install -Dmaven.test.skip=true"

script:
  - "mvn org.jacoco:jacoco-maven-plugin:$JACOCO_VERSION:prepare-agent install"

after_success:
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_BRANCH == quality ]] && mvn sonar:sonar"
