language: java

addons:
  sonarqube:
    token: $SONARQUBE_TOKEN

jdk:
  - oraclejdk8

before_script:
  - "mvn clean install -Dmaven.test.skip=true"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
